name: BabyMode
version: '${project.version}'
main: pl.pomoku.babymode.Main
api-version: 1.18
authors: [ HubiRto ]
description: Plugin na latwiejsza rozgrywke
commands:
    babymode:
        aliases:
            - 'bm'